import { Category } from './types';

export const DEFAULT_CATEGORIES: Category[] = [
  { id: '1', name: 'Food', color: '#ef4444', isCustom: false },
  { id: '2', name: 'Transport', color: '#f59e0b', isCustom: false },
  { id: '3', name: 'Groceries', color: '#10b981', isCustom: false },
  { id: '4', name: 'Shopping', color: '#3b82f6', isCustom: false },
  { id: '5', name: 'Bills', color: '#6366f1', isCustom: false },
  { id: '6', name: 'Entertainment', color: '#8b5cf6', isCustom: false },
  { id: '7', name: 'Health', color: '#ec4899', isCustom: false },
  { id: '8', name: 'Others', color: '#6b7280', isCustom: false },
];

export const CURRENCY_SYMBOL = '₹';

export const KEYWORD_RULES: Record<string, string> = {
  'uber': 'Transport',
  'ola': 'Transport',
  'auto': 'Transport',
  'lyft': 'Transport',
  'bus': 'Transport',
  'train': 'Transport',
  'metro': 'Transport',
  'gas': 'Transport',
  'fuel': 'Transport',
  'petrol': 'Transport',
  'burger': 'Food',
  'pizza': 'Food',
  'coffee': 'Food',
  'starbucks': 'Food',
  'swiggy': 'Food',
  'zomato': 'Food',
  'restaurant': 'Food',
  'walmart': 'Groceries',
  'target': 'Groceries',
  'grocery': 'Groceries',
  'blinkit': 'Groceries',
  'zepto': 'Groceries',
  'whole foods': 'Groceries',
  'netflix': 'Entertainment',
  'hulu': 'Entertainment',
  'spotify': 'Entertainment',
  'cinema': 'Entertainment',
  'movie': 'Entertainment',
  'doctor': 'Health',
  'pharmacy': 'Health',
  'gym': 'Health',
  'medicine': 'Health',
  'rent': 'Bills',
  'electric': 'Bills',
  'water': 'Bills',
  'internet': 'Bills',
  'phone': 'Bills',
  'amazon': 'Shopping',
  'flipkart': 'Shopping',
  'myntra': 'Shopping',
  'cloth': 'Shopping',
};